### ISSUE TITLE
no main manifest attribute, in /usr/share/java/guice.jar

### ISSUE THREAD

**Issue by nakagit** [mnemonic-no/act-platform#2]
Hi!

I'm stacked on the last line.  I executed following command:
`java -Dapplication.properties.file=/opt/act-platform/executable/application.properties.localhost -jar /usr/share/java/guice.jar module=no.mnemonic.act.platform.rest.RestModule module=no.mnemonic.act.platform.service.ServiceModule`
**no main manifest attribute, in /usr/share/java/guice.jar**

Do I need to point other jar file, instead of '/usr/share/java/guice.jar'?

Please have a look the find result here:
![find_jar](https://user-images.githubusercontent.com/10558255/53133888-3d499d80-35b8-11e9-973a-e31887534be7.png)

Kind regards,
Yuki

**Comment by ko-mueller** [comment]
Hi!

The correct command to start the application should be:
`java -Dapplication.properties.file=/opt/act-platform/executable/application.properties.localhost -jar /opt/act-platform/executable/target/act-platform-0.0.1-SNAPSHOT.jar guice module=no.mnemonic.act.platform.rest.RestModule module=no.mnemonic.act.platform.service.ServiceModule`
You might need to change the path after the -jar switch depending on where the compiled jar is on you file system. It should be in the /executable/target folder. The compiled jar contains Guice and the correct startup class will be picked up automatically. You probably need to start the application from the /executable folder, otherwise it won't find some of the other configuration files (or change the paths in application.properties.localhost).

Kind regards,
Konstantin

**Comment by nakagit** [comment]
Hi!

Thanks for your prompt answer.

root@kali2018:/opt/act-platform/executable# `java -Dapplication.properties.file=/opt/act-platform/executable/application.properties.localhost -jar /opt/act-platform/executable/target/act-platform-0.0.1-SNAPSHOT.jar guice module=no.mnemonic.act.platform.rest.RestModule module=no.mnemonic.act.platform.service.ServiceModule`
******************************************
Bootstrap 0.0.1-SNAPSHOT
******************************************
no.mnemonic.commons.component.ComponentException: java.lang.RuntimeException: Could not perform request to create index.
	at no.mnemonic.commons.container.ComponentContainer.activate(ComponentContainer.java:337)
	at no.mnemonic.commons.container.ComponentContainer.initialize(ComponentContainer.java:165)
	at no.mnemonic.commons.container.BootStrap.bootContainer(BootStrap.java:181)
	at no.mnemonic.commons.container.BootStrap.guiceBoot(BootStrap.java:163)
	at no.mnemonic.commons.container.BootStrap.boot(BootStrap.java:109)
	at no.mnemonic.commons.container.BootStrap.main(BootStrap.java:65)
Caused by: java.lang.RuntimeException: Could not perform request to create index.
	at no.mnemonic.act.platform.dao.elastic.FactSearchManager.logAndExit(FactSearchManager.java:920)
	at no.mnemonic.act.platform.dao.elastic.FactSearchManager.createIndex(FactSearchManager.java:383)
	at no.mnemonic.act.platform.dao.elastic.FactSearchManager.startComponent(FactSearchManager.java:112)
	at no.mnemonic.commons.container.plugins.impl.ComponentLifecycleAspectHandler.startComponent(ComponentLifecycleAspectHandler.java:18)
	at no.mnemonic.commons.container.ComponentContainer.startNode(ComponentContainer.java:359)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at no.mnemonic.commons.container.ComponentContainer.activate(ComponentContainer.java:332)
	... 5 more
Caused by: org.elasticsearch.client.ResponseException: PUT http://localhost:9200act: HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.mapping.single_type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"}],"type":"illegal_argument_exception","reason":"unknown setting [index.mapping.single_type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"},"status":400}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)

![elasticsearch_error](https://user-images.githubusercontent.com/10558255/53153544-dc43b900-35fb-11e9-93e7-af2afa648c58.png)

Gee, I've got above error, I'm sure Elasticsearch is working as following:
![elasticsearch_working](https://user-images.githubusercontent.com/10558255/53153725-5a07c480-35fc-11e9-8018-c795140833cd.png)

docker ps command result is here:
![docker_ps](https://user-images.githubusercontent.com/10558255/53154107-51fc5480-35fd-11e9-9d6d-6ba978bb55b3.png)

In order to investigate the error, I'll get any information you'd like to know. So, please let me know. I'm willing to fix this.

Many thanks,
Yuki

**Comment by ko-mueller** [comment]
Hi!

The reason for this error is that you are using Elasticsearch 6.6 but the platform requires Elasticsearch 5.6 right now. It should mostly work with 6.6 but I haven't tested it properly and I need to upgrade the client driver as well. The upgrade is on my roadmap but I just didn't had the time yet. For now I suggest to downgrade Elasticsearch to version 5.6.

Kind regards,
Konstantin

**Comment by nakagit** [comment]
Hi!

Thank you for your big help.  :)

I downgraded Elasticsearch 5.6.15, then previous error has gone. 
And also, downgrade Cassandra 2.2.14.

Then, I executed following command:
`# java -Dapplication.properties.file=/opt/act-platform/executable/application.properties.localhost -jar /opt/act-platform/executable/target/act-platform-0.0.1-SNAPSHOT.jar guice module=no.mnemonic.act.platform.rest.RestModule module=no.mnemonic.act.platform.service.ServiceModule`

But, I'm afraid I couldn't see any messages as following:
![act_nomessages](https://user-images.githubusercontent.com/10558255/53200825-dedaf880-3665-11e9-90a6-975e2dbb2635.png)



I'm wondering about docker port 2375. I didn't configure anything about port 2375.
Do I need to do something for docker port 2375?


Any advices will be helpful. 


Kind regards,
Yuki

**Comment by ko-mueller** [comment]
Hi!

You don't need to downgrade Cassandra, the newest version should be fine. The code has never be tested with such an old version of Cassandra. Port 2375 is the port to communicate with the Docker daemon. If you can start/stop containers it works correctly.

If you don't see any messages in the console it hopefully means that the application has started correctly. You can check the logs/service.log file for any error messages. Regular application logs go into this file.

Kind regards,
Konstantin

**Comment by nakagit** [comment]
Hi!

Fortunately, I didn't find any error messages at ./logs/service.log file.

Kind regards,
Yuki
